version: '3'
services:

  #PHP Service
  app:
    image: chapacua/php:0.2
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default
  #Nginx Service
  webserver:
    image: chapacua/nginx:0.2
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
      
#Docker Networks
networks:
    default:
      external: true
      name: db_net_apps